spring:
 application:
  name: flashcardadmin
 servlet:
  multipart:
   max-file-size: 20MB
   max-request-size: 25MB
 datasource:
   url: jdbc:mysql://mysql-26a06367-neekon250803.j.aivencloud.com:12350/flashcard?sslmode=require
   username: avnadmin
   password: ${}
server:
  address: ${}
  port: 8080
app:
  cors:
    origins: http://${}:8080